{
 "title": "HashiCups Performance Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "default, consul" },
   { "name": "app", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", image!=\"\", pod!=\"\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Envoy Connections/sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(envoy_listener_downstream_cx_total{namespace=~\"$namespace\"}[$__interval]) ",
     "legendFormat": "{{consul_source_datacenter}} : {{namespace}} : {{consul_source_service}} : {{envoy_listener_address}}"
    }
   ]
  },
  {
   "title": "Network Bytes Rx and Tx by pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"default\"}[5m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(node_network_receive_drop_total{component=\"node-exporter\"}[5m]))",
     "legendFormat": "global-dropped-pkts"
    }
   ]
  },
  {
   "title": "Requests Active (Upstream)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_active{}) by (namespace,consul_source_service,envoy_cluster_name)",
     "legendFormat": "{{namespace}} : {{consul_source_service}} : {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Upstream Rq Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum by(namespace,app)(rate(envoy_cluster_upstream_rq_total{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{namespace}}:{{app}}"
    }
   ]
  },
  {
   "title": "Downstream Rq Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total{namespace=~\"$namespace\",envoy_http_conn_manager_prefix=\"public_listener\"}[5m])) by (app, namespace)\n",
     "legendFormat": "{{namespace}}:{{app}}"
    }
   ]
  }
 ]
}