---
apiVersion: v1
kind: Service
metadata:
  name: product-api-db
  namespace: default
  labels:
    app: product-api-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: product-api-db
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: product-api-db
  namespace: default
spec:
  protocol: "tcp"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-api-db
  namespace: default
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: product-api-db
      app: product-api-db
  template:
    metadata:
      labels:
        service: product-api-db
        app: product-api-db
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/enable-metrics-merging: "true"
        consul.hashicorp.com/service-metrics-port: "9187"
        #consul.hashicorp.com/service-metrics-path: "/metrics"
    spec:
      serviceAccountName: product-api-db
      containers:
        - name: product-api-db
          image: hashicorpdemoapp/product-api-db:v0.0.22
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: products
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "pgdata"
        - name: jaeger-agent
          image: jaegertracing/jaeger-agent:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5775
            name: zk-compact-trft
            protocol: UDP
          - containerPort: 5778
            name: config-rest
            protocol: TCP
          - containerPort: 6831
            name: jg-compact-trft
            protocol: UDP
          - containerPort: 6832
            name: jg-binary-trft
            protocol: UDP
          - containerPort: 14271
            name: admin-http
            protocol: TCP
          args:
          - --reporter.grpc.host-port=dns:///tempo.grafana.svc.cluster.local:14250
          - --reporter.type=grpc
        - name: postgres-exporter
          image: 'prometheuscommunity/postgres-exporter:v0.11.0'
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://postgres:password@localhost:5432/postgres?sslmode=disable"
          ports:
            - containerPort: 9113
      volumes:
        - name: pgdata
          emptyDir: {}
