{
 "title": "Envoy Performance",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Mem Usage % by pod limits",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * max (container_memory_working_set_bytes{namespace=\"$namespace\"} / on(container, pod) label_replace(kube_pod_container_resource_limits{resource=\"memory\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\")) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Usage by pod limits",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * max(\n  rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[5m])\n    / on (container, pod)\n  label_replace(kube_pod_container_resource_limits{resource=\"cpu\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\")\n) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Throttled Seconds - small",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"fortio-server-small.*\", container=\"consul-dataplane\"}[5m])",
     "legendFormat": "CPU Throttled Seconds"
    }
   ]
  },
  {
   "title": "Dataplane Latency 50%",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le,app) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=\"$namespace\"}[5m])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dataplane Latency 75%",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(le,app) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=\"$namespace\"}[5m])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dataplane Latency 90%",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(le,app) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=\"$namespace\"}[5m])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dataplane Latency 99.9%",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by(le, app) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=\"$namespace\"}[5m])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Bytes Rx and Tx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{pod=~\"fortio-server-defaults.*\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{pod=~\"fortio-server-defaults-.*\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(envoy_http_downstream_cx_total{pod=~\"fortio-server.*|fortio-server-defaults-ff55bff89-qrbst\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU Utilization Consul dataplane container - Defaults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"consul-dataplane\", pod=~\"fortio-server-defaults.*\"}[5m])",
     "legendFormat": "CPU Usage "
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=~\"fortio-server-defaults.*\", resource=\"cpu\", container=\"envoy-sidecar\"}",
     "legendFormat": "CPU Resource Limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{pod=~\"fortio-server-defaults.*\", resource=\"cpu\", container=\"envoy-sidecar\"}",
     "legendFormat": "CPU Resource Request"
    }
   ]
  },
  {
   "title": "Dataplane Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{pod=~\"fortio-server-defaults.*\", container=\"consul-dataplane\"}",
     "legendFormat": "Memory Max Usage {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", pod=~\"fortio-server.*\", container=\"envoy-sidecar\"}",
     "legendFormat": "Memory Limit {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\", pod=~\"fortio-client.*\", container=\"envoy-sidecar\"}",
     "legendFormat": "Memory Request {{pod}}"
    }
   ]
  }
 ]
}