{
 "title": "HashiCups Performance Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,exported_namespace)"
    }
   },
   { "name": "app", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 0 },
   "options": {
    "content": "# Health Monitoring Visualizations"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "# Performance Monitoring Visualizations"
   }
  },
  {
   "title": "Total active HTTP downstream connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active{app=~\"$app\"}) by (app)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Envoy cluster state",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_total)-sum(envoy_cluster_membership_healthy)) == bool 0"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (app) (envoy_cluster_upstream_cx_active{app=\"$app\",namespace=~\"$namespace\",envoy_cluster_name!~\"consul-dataplane|prometheus.*|local_app|original-.*\"})",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "CPU Throttled seconds by pod",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace\", container=\"consul-dataplane\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Requests Active (Upstream)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_active{}) by (namespace,consul_source_service,envoy_cluster_name)",
     "legendFormat": "{{namespace}} : {{consul_source_service}} : {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Total active upstream connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active) by (app,envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}} ({{service}})"
    }
   ]
  },
  {
   "title": "Envoy Connections/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(envoy_listener_downstream_cx_total{namespace=~\"$namespace\"}[$__interval]) ",
     "legendFormat": "{{consul_source_datacenter}} : {{namespace}} : {{consul_source_service}} : {{envoy_listener_address}}"
    }
   ]
  },
  {
   "title": "Running services",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(envoy_server_live)" }
   ]
  },
  {
   "title": "Downstream Rq Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total{namespace=~\"$namespace\",envoy_http_conn_manager_prefix=\"public_listener\"}[5m])) by (app, namespace)\n",
     "legendFormat": "{{namespace}}:{{app}}"
    }
   ]
  },
  {
   "title": "Connections Rejected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(envoy_listener_downstream_cx_overload_reject{}[$__interval])",
     "legendFormat": "{{namespace}} : {{consul_source_service}}-{{envoy_listener_address}}-overload"
    },
    {
     "expr": "rate(envoy_listener_downstream_global_cx_overflow{}[$__interval])",
     "legendFormat": "{{namespace}} : {{consul_source_service}}-{{envoy_listener_address}}-overflow"
    }
   ]
  },
  {
   "title": "Cert Expiration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "envoy_server_days_until_first_cert_expiring{} ",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Requests / sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total{namespace=~\"$namespace\",envoy_http_conn_manager_prefix=\"public_listener\"}[5m])) by (namespace)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$app - Latency by Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_count{namespace=~\"$namespace\",envoy_cluster_name!~\"prometheus_backend|local_app\"}[5m])) - on() sum(rate(envoy_cluster_upstream_rq_time_bucket{le=\"1\",envoy_cluster_name!~\"prometheus_backend|local_app\",namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "<1ms"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_count{namespace=~\"$namespace\",envoy_cluster_name!~\"prometheus_backend|local_app\"}[5m])) - on() sum(rate(envoy_cluster_upstream_rq_time_bucket{le=\"5\",envoy_cluster_name!~\"prometheus_backend|local_app\",namespace=~\"$namespace\"}[5m]))\n",
     "legendFormat": "<5ms"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_count{namespace=~\"$namespace\",envoy_cluster_name!~\"prometheus_backend|local_app\"}[5m])) - on() sum(rate(envoy_cluster_upstream_rq_time_bucket{le=\"10\",envoy_cluster_name!~\"prometheus_backend|local_app\",namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "<10ms"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_count{namespace=~\"$namespace\",envoy_cluster_name!~\"prometheus_backend|local_app\"}[5m])) - on() sum(rate(envoy_cluster_upstream_rq_time_bucket{le=\"25\",envoy_cluster_name!~\"prometheus_backend|local_app\",namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "<25ms"
    }
   ]
  },
  {
   "title": "Upstream Rq Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 13, "y": 39 },
   "targets": [
    {
     "expr": "sum by(namespace,app)(rate(envoy_cluster_upstream_rq_total{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{namespace}}:{{app}}"
    }
   ]
  },
  {
   "title": "Downstream Rq by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"public_listener\"}[5m])) by (namespace, app,envoy_response_code_class)\n",
     "legendFormat": "{{namespace}} : {{app}}-{{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Network Bytes Rx and Tx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 13, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$app.*\"}[5m])",
     "legendFormat": "{{pod}}-rx"
    },
    {
     "expr": "- rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$app.*\"}[5m])",
     "legendFormat": "{{pod}}-tx"
    },
    {
     "expr": "sum(rate(node_network_receive_drop_total{component=\"node-exporter\"}[5m]))",
     "legendFormat": "global-dropped-pkts"
    }
   ]
  },
  {
   "title": "Upstream Rq by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum by(namespace,app,envoy_response_code_class) (rate(envoy_cluster_upstream_rq_xx[5m]))",
     "legendFormat": "{{namespace}} : {{app}}-{{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "CPU Usage by container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\",image!=\"\", container!=\"\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Envoy Config Stale",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "group(envoy_control_plane_connected_state{namespace=~\"$namespace\"}) by (local_cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem Usage % by pod limits",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * max (container_memory_working_set_bytes{namespace=~\"$namespace\"} / on(container, pod) label_replace(kube_pod_container_resource_limits{resource=\"memory\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\")) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GRPC Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "sum by (app)(rate(envoy_listener_http_fortio_server_defaults_grpc_fortio_consul_default_dc1_downstream_rq_xx{envoy_response_code_class=~\"1|3|4|5\"}[$__rate_interval]))",
     "legendFormat": "{{app}}-errors"
    },
    {
     "expr": "rate(envoy_listener_http_fortio_server_defaults_grpc_fortio_consul_default_dc1_downstream_rq_xx{envoy_response_code_class=\"2\"}[$__rate_interval])",
     "legendFormat": "{{app}}-success"
    }
   ]
  },
  {
   "title": "HTTP Status ( $app )",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum by(app, envoy_response_code_class) (increase(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"public_listener\", namespace=~\"$namespace\", app=~\"$app\"}[5m]))",
     "legendFormat": "{{app}}-{{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Dataplane Latency ( $app )",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$namespace\", app=~\"$app\"}[5m])))\n",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$namespace\", app=~\"$app\"}[5m])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$namespace\", app=~\"$app\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(.999, sum by(le) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$namespace\", app=~\"$app\"}[5m])))",
     "legendFormat": "p99.9"
    }
   ]
  }
 ]
}